name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'output/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        # This is the branch that has the code for this article
        src_branch: generating-design-token-theme-shades-with-style-dictionary
        src_path: output/css/_variables.css
        dst_owner: michaelmang
        dst_repo_name: design-token-theme-shades
        dst_branch: implement-shades
        dst_path: tokens/_variables.css
        username: michaelmang
        email: mikemangialardi94@gmail.com
        commit_message: Update platform deliverable