# .github/workflows/export-tokens-on-input.yml
name: Generate Tokens On Input

on:
  push:
    paths:  
      - 'input/design-tokens.json'
jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
    - name: Install Node Dependencies
      run: npm install
    - name: Build Style Dictionary
      run: npm run build
    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update platform deliverables